### ISSUE TITLE
Floppy gets overwritten with multiple parallel runs

### ISSUE THREAD

**Issue by agowa** [hashicorp/packer-plugin-vsphere#93]
#### Overview of the Issue

When two or more packer instances are executed simultaneously for different projects against the same vsphere server the floppy file gets overwritten.

#### Reproduction Steps

1. Create a simple packer project for a deployment that uses a floppy
2. Copy this project and rename the vm in the copy to get two independent projects
3. Start deploy both projects simultaneously
4. Now the build may fail, disk gets removed while mid-deployment. Also when looking into vsphere logs it can be observed that the floppy files are used by something else (aka. that they're locked)
```
Description:
07/30/2021, 3:36:55 PM Warning message on Win server 2016 standard template Core (english) - latest on <SERVER> in <DC> : Cannot open floppy image packer-tmp-created-floppy.flp: 4 (Interrupted system call)
Event Type Description:
A warning message listing a collection of observations has been reported by the virtual machine
Possible Causes:
The event contains details on why this warning was issued
Related events:
There are no related events.
```
as well as
```
Description:
07/30/2021, 3:36:55 PM Warning message on Win server 2016 standard template Core (english) - latest on <SERVER> in <DC> : Could not connect to floppy "packer-tmp-created-floppy.flp". It is being used by another virtual machine or some other program. It will start disconnected.
Event Type Description:
A warning message listing a collection of observations has been reported by the virtual machine
Possible Causes:
The event contains details on why this warning was issued
Related events:
There are no related events.
```

### Plugin and Packer version

`Packer v1.7.4`

### Operating system and Environment details

OS, Architecture, and any other information you can provide about the
environment.
GitLab CI pipeline
```
image: ubuntu:latest

stages:
  - build

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean  # Re-enable apt cache
  - apt update
  - apt install -y wget ca-certificates gzip tar openssl lsb-release gnupg
  - wget -q -O - https://apt.releases.hashicorp.com/gpg | apt-key add -
  - echo "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main" >> /etc/apt/sources.list
  - apt update
  - apt install packer

build_vsphere_2019_standard_core_images: &build_vsphere_2019_standard_core_images
  stage: build
  script:
    - packer init -upgrade win_2019_standard_core.pkr.hcl
    - packer build -force -only='vsphere-iso.*' -timestamp-ui win_2019_standard_core.pkr.hcl
  only:
    - master
  environment:
    name: production

build_vsphere_2019_standard_gui_images: &build_vsphere_2019_standard_gui_images
  stage: build
  script:
    - packer init -upgrade win_2019_standard_gui.pkr.hcl
    - packer build -force -only='vsphere-iso.*' -timestamp-ui win_2019_standard_gui.pkr.hcl
  only:
    - master
  environment:
    name: production
```

### Log Fragments and crash.log files

Packer doesn't crash, building the VM fails (race conditions, see above).
